---
- name: Output Automation Controller Configs
  hosts: all
  gather_facts: false
  vars:
    controller_api_plugin: ansible.controller.controller_api
  
  pre_tasks:
    - name: "Setup authentication (block)"
      no_log: "{{ controller_configuration_filetree_create_secure_logging | default('false') }}"
      when: aap_oauthtoken is not defined
      tags:
        - always
      block:
        - name: "Get the Authentication Token for the future requests"
          ansible.builtin.uri:
            url: "https://192.168.122.14/api/v2/tokens/"
            user: admin
            password: redhat
            method: POST
            force_basic_auth: true
            validate_certs: false
            status_code: 201
          register: authtoken_res

        - name: "Set the oauth token to be used since now"
          ansible.builtin.set_fact:
            aap_oauthtoken: "{{ authtoken_res.json.token }}"
            controller_oauthtoken: "{{ authtoken_res.json.token }}"
            aap_oauthtoken_url: "{{ authtoken_res.json.url }}"

    - name: Recursively remove output directory
      ansible.builtin.file:
        path: /home/svc-ansibletower/AAP/export
        state: absent
